Move up verify step

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -61,10 +61,10 @@ jobs:
       - name: build
         run: pnpm build
         
+      - name: verify build
+        run: if [ ! -x ./_esy/default/build/default/Main.exe ]; then echo "Executable not found" && exit 1; else echo "Build succeeded ✅"; fi
+
       - name: Setting dependency cache
         run: |
           pnpm exec esy export-dependencies
         if: steps.restore-cache.outputs.cache-hit != 'true'
-
-      - name: verify build
-        run: if [ ! -x ./_esy/default/build/default/Main.exe ]; then echo "Executable not found" && exit 1; else echo "Build succeeded ✅"; fi
