ugh

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,11 +32,14 @@ jobs:
           version: 6.29.0
           run_install: true
 
-      - name: build
-        run: pnpm exec esy && pnpm build
+      - name: Esy bootstrap
+        run: pnpm exec esy install
+
+      - name: Esy build 
+        run: pnpm exec esy dune build
         
-      - name: verify build
-        run: if [ ! -x ./_esy/default/build/default/Main.exe ]; then echo "Executable not found" && exit 1; else echo "Build succeeded ✅"; fi
+      # - name: verify build
+      #   run: if [ ! -x ./_esy/default/build/default/Main.exe ]; then echo "Executable not found" && exit 1; else echo "Build succeeded ✅"; fi
 
       - name: Upload binary
         uses: actions/upload-artifact@v2
